# Generated by Django 3.1 on 2020-08-25 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Task Name')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('stop_time', models.DateTimeField(verbose_name='Stop Time')),
                ('elapse_time', models.DateTimeField(verbose_name='Elapse Time')),
                ('memo', models.TextField(verbose_name='Memo')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleApp.person')),
            ],
        ),
    ]
